- hosts: 163.74.92.105
  vars: 
    git_repo: 'https://github.com/drewmibm/ansible-flask-demo.git'
    remote_project_path: /home/itzuser/demoapp/
    requirements_path: /home/itzuser/demoapp/requirements.txt
    venv_path: /home/itzuser/demoapp/venv
    service_file: demoAppServices.service
    nginx_base_config: nginx.conf
    nginx_config: demoAppRequests.conf
    user: itzuser
  become: yes
  tasks:
    # - name: Update and upgrade dnf packages
    #   become: true
    #   dnf:
    #     update_cache: yes

    - name: Get repository from git and update locally
      ansible.builtin.git:
        repo: "{{git_repo}}"
        dest: "{{remote_project_path}}"
        clone: yes
        update: yes
        accept_hostkey: true

    - name: open folder permissions
      ansible.builtin.file:
        path: "{{remote_project_path}}"
        mode: "0777"
        recurse: yes

    - name: Install specified python requirements in indicated virtualenv
      ansible.builtin.pip:
        virtualenv_command: python3 -m venv
        requirements: "{{requirements_path}}"
        virtualenv: "{{venv_path}}"

    - name: Copy service file with owner and permissions to server
      ansible.builtin.copy:
        src: "{{service_file}}"
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0777'
        

    - name: Start gunicorn service
      systemd:
        name: "{{service_file}}"
        state: restarted
        daemon_reload: yes
        

    - name: Enable gunicorn service
      systemd:
        name: "{{service_file}}"
        enabled: true
        

    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx

    - name: copy base nginx conf to /etc/nginx
      ansible.builtin.copy:
        src: "{{nginx_base_config}}"
        dest: /etc/nginx/{{nginx_base_config}}
        owner: root
        group: root
        mode: '0777'

    - name: copy configuration to nginx
      ansible.builtin.copy:
        src: "{{nginx_config}}"
        dest: /etc/nginx/conf.d/{{nginx_config}}
        owner: root
        group: root
        mode: '0777'

    - name: Set httpd_can_network_connect flag on and keep it persistent across reboots
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: true
        persistent: true

    - name: Start nginx
      systemd:
        name: nginx
        state: restarted