- hosts: 163.74.92.105
  vars: 
    git_repo: 'https://github.com/drewmibm/ansible-flask-demo.git'
    remote_project_path: /home/itzuser/demoapp/
    requirements_path: /home/itzuser/demoapp/requirements.txt
    venv_path: /home/itzuser/demoapp/venv
    service_file: demoAppServices.service
    nginx_base_config: nginx.conf
    nginx_config: demoAppRequests.conf
    user: itzuser
  become: yes
  tasks:
  
    - name: pull git_repo to remote_project_path and accept new host key
      ansible.builtin.git:
        repo: "{{ git_repo }}"
        dest: "{{ remote_project_path }}"
        accept_hostkey: true
    
      
    
    - name: install specified python requirements in indicated venv 
      ansible.builtin.pip:
        requirements: "{{ requirements_path }}"
        virtualenv: "{{ venv_path }}"
        virtualenv_python: python3
    
      
    
    - name: copy service file with root owner and '0777' permissions to /etc/systemd/system
      ansible.builtin.template:
        src: "{{ service_file }}"
        dest: /etc/systemd/system/demoAppServices.service
        owner: root
        group: root
        mode: '0777'

    - name: use the first three tasks to copy the service file
      ansible.builtin.include_tasks:
        file: copy_service_file.yml
    
    
      
    
    - name: start service_file service
      ansible.builtin.systemd:
        name: demoAppServices.service
        state: started
        daemon_reload: true
        enabled: true
    

      
    
    - name: install nginx
     
    
    - name: copy nginx_base_config to /etc/nginx owner and group root with "0777" permissions
      
    
    - name: copy nginx_config to /etc/nginx/conf.d owner and group root with "0777" permissions
      
    
    - name: set selinux http_can_network_connect flag on and keep it persistant across reboots
      
    
    - name: start nginx service
      
    






